require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'GovTechWallet' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )


  target 'GovTechWalletTests' do
    inherit! :complete
    # Pods for testing
  end

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Firebase/Crashlytics'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()
  use_flipper!({'Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1'})

  post_install do |installer|
    react_native_post_install(installer)
  end
end